build:
  environment:
    node: v13.9.0
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override: [js-scrutinizer-run]
    coverage:
      services:
        mongo: 4.4.1
      tests:
        before:
          - command: 'git clone https://github.com/sonnerberg/jsramverk-project-backend backend'
          - command: 'npm install --prefix backend'

        override:
          - command: 'npm run start:test --prefix backend'
            background: true
          - command: 'npm run start'
            background: true
          - command: npm test
            coverage:
              file: coverage/clover.xml
              format: clover
